name: Generate Data

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout original repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install gspread oauth2client pandas scikit-learn faker requests numpy --upgrade

      - name: Clone Lab2 repository
        run: git clone https://${{ secrets.GH_TOKEN }}@github.com/PJATK-ASI-2024/Lab2---Obr-bka-danych.git

      - name: Run data processing script
        run: |
          cd Lab2---Obr-bka-danych
          python3 generator_danych.py -s 25278

      - name: Upload CSV to Google Sheets
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: |
          echo "$GOOGLE_SHEETS_CREDENTIALS" > creds.json
          python3 SendData.py

      - name: Clean up credentials
        run: rm creds.json
